# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  integrationtest:
    docker:
      - image: circleci/openjdk:8u171-jdk-browsers
    working_directory: ~/repo
    
    machine:
        # Override /etc/hosts
    hosts:
      localhost: 127.0.0.1

    steps:
      - checkout
 

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # run tests!

      - run:  ./startwebserver.sh

      - run:  sleep 500

      - run:  mvn -U -DskipTests=true clean install

      - run:  mvn -U clean verify -Dcucumber.filter.tags=@test -Dserenity.project.name="Serenity-Rest" -Drestapi.baseurl=http://localhost:8080/webapp

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - store_test_results:
          path: target

      - aws-s3/copy:
          arguments: '--recursive --acl public-read-write'
          from: target/site/serenity
          to: 's3://serenitybdd'


      # - slack/status:
      #     fail_only: false
      #     mentions: 'LayMui'
      #     failure_message: "see latest report: http://serenitybdd.s3-website-ap-southeast-1.amazonaws.com/index.html"
      #     webhook: $SLACK



orbs:
  slack: circleci/slack@4.4.4
  aws-s3: circleci/aws-s3@2.0.0

workflows:
  version: 2
  integrationtest:
    jobs:
      - integrationtest